name: Build and deploy ASP app to Azure Web App - gescalante1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.1.4  # Actualizaci贸n a la versi贸n compatible con Node.js 20

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.2  # Actualizaci贸n a la versi贸n compatible con Node.js 20

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=$(System.DefaultWorkingDirectory)/published /p:Configuration=Release /p:TargetFrameworkVersion=v4.8

      - name: List published files
        run: dir $(System.DefaultWorkingDirectory)/published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: $(System.DefaultWorkingDirectory)/published/**

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: List downloaded files
        run: dir ASP-app

      - name: Install Azure CLI
        run: |
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
          Start-Process msiexec.exe -ArgumentList '/I .\AzureCLI.msi /quiet' -Wait

      - name: Verify Azure CLI Installation
        run: az --version

      - name: Login to Azure using Service Principal
        uses: azure/login@v1.5.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'gescalante1'
          package: ASP-app
